language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
script:
- yarn generate
deploy:
  provider: firebase
  token:
    secure: "O9KsWQ+GizaKtzc1oXEIRWGhAcS09i1TQWwB74qROm1KA/zY1Hyx68197JIr3Hse4KtjfCvK6VR+FivZeJiKS4rMJ7b3Ogo5mabrq7RJTrwoIXocqNQEypZpZmLbL/LXgvWyg+1WbyqT3abTuR68XW6s34bOquv3YJrECQXuTmREraaKd1TpueF68aVBtrNnTqpEFZd+R8gINjB4VQ/NHgztz4ldWJDM3K9SZRUmxkXO34wek2NnQcCMFgptbwtvrJqW1uqEhkiuQSCiBjA1U24nTaj026q9RNo/HxiXTYBmEeXnr9hdfCG1Q0pESQciFj6WMTRgbFGoOvi6UWfJsAayWZjLUk8wubkRl4jsoDtmZ2RcFAgneSdMd0Z8BDeC5R1TRDSRMTWFA8pHu9LssnSgQm2SqOXlz/7NsfJs2VuVyqSUrOMHmNDBNLcxEDVir17nJFrqTd1LeLrDfL9tc/IwOV+0VAJdpqVSuowg1+wojfceR1Xpf2HpkR/Cu9RML07Uc4SzZjoH3Q1GMWUvnTtv3bmbmCvn6j99d38D93yRyyOsnUAg/oBPShI6OaMO2SFniDh/J3f2VNo7kRYS2JjDrUqpPFYFUzZXLUOCckrdrQ6f84z2dZzHIF1zeEucb5wGYJXAnbYeky2AQzo8WeXqhVW1sWN53Ysg9WGp+ME="
  project: projecthtml-c5be3
  message: "Test message"
