language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
before_script:
   - npm install -g firebase-tools
script:
- yarn generate
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
